name: CI
on: push

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup deno
              uses: denoland/setup-deno@v2

            - name: Cache dependencies
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.deno
                      ~/.cache/deno
                  key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}

            - name: Install dependencies
              run: deno install

            - name: Build
              run: deno run build

            - name: Test imports
              run: deno run test

            - name: Check types
              run: deno check

            - name: Check formatting
              run: deno fmt --check
