name: CI
on: push

jobs:
    builds:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deno
            - run: deno run build

    tests:
        needs: builds
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deno
            - run: deno run test

    types:
        needs: tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deno
            - run: deno check

    formatting:
        needs: types
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/actions/deno
            - run: deno fmt --check
