name: Lint
on:
    push:
        branches: [workflow]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: biomejs/setup-biome@v2
              with:
                  version: latest
            - run: biome ci
